apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: olla-backend
  namespace: envoy-ai-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: olla-svc.ai-local.svc.cluster.local
        port: 40114
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: litellm-backend
  namespace: envoy-ai-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: litellm-svc.ai-cloud.svc.cluster.local
        port: 4000
