apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc-01
  namespace: ai-local
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc-02
  namespace: ai-local
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc-03
  namespace: ai-local
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 100Gi
