apiVersion: v1
kind: Namespace
metadata:
  name: ai-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-cloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-ai-gateway-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
